<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Courses extends \App\Entity\Courses implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'certificates' => [parent::class, 'certificates', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'enrollments' => [parent::class, 'enrollments', null],
        "\0".parent::class."\0".'hours' => [parent::class, 'hours', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'instructor' => [parent::class, 'instructor', null],
        "\0".parent::class."\0".'lessons' => [parent::class, 'lessons', null],
        "\0".parent::class."\0".'minutes' => [parent::class, 'minutes', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'certificates' => [parent::class, 'certificates', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'enrollments' => [parent::class, 'enrollments', null],
        'hours' => [parent::class, 'hours', null],
        'id' => [parent::class, 'id', null],
        'instructor' => [parent::class, 'instructor', null],
        'lessons' => [parent::class, 'lessons', null],
        'minutes' => [parent::class, 'minutes', null],
        'title' => [parent::class, 'title', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
