<?php

namespace Container2YjrWxR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8z08cwr.App\Entity\Certificate' shared service.
     *
     * @return \App\Entity\Certificate
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8z08cwr": it needs an instance of "App\\Entity\\Certificate" but this type has been excluded in "config/services.yaml".');
    }
}
