<?php

namespace ContainerZmxKwhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5m8zpMLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5m8zpML' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5m8zpML'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'profile' => ['privates', '.errored..service_locator.5m8zpML.App\\Entity\\Profile', NULL, 'Cannot autowire service ".service_locator.5m8zpML": it needs an instance of "App\\Entity\\Profile" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'profile' => 'App\\Entity\\Profile',
            'slugger' => '?',
        ]);
    }
}
