<?php

namespace ContainerZmxKwhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M8dTPVrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m8dTPVr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m8dTPVr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lessonsRepository' => ['privates', 'App\\Repository\\LessonsRepository', 'getLessonsRepositoryService', true],
        ], [
            'lessonsRepository' => 'App\\Repository\\LessonsRepository',
        ]);
    }
}
