<?php

namespace ContainerZmxKwhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2uKfIyEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2uKfIyE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2uKfIyE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificateRepository' => ['privates', 'App\\Repository\\CertificateRepository', 'getCertificateRepositoryService', true],
            'enrollmentsRepository' => ['privates', 'App\\Repository\\EnrollmentsRepository', 'getEnrollmentsRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lesson' => ['privates', '.errored..service_locator.2uKfIyE.App\\Entity\\Lessons', NULL, 'Cannot autowire service ".service_locator.2uKfIyE": it needs an instance of "App\\Entity\\Lessons" but this type has been excluded in "config/services.yaml".'],
            'lessonsRepository' => ['privates', 'App\\Repository\\LessonsRepository', 'getLessonsRepositoryService', true],
        ], [
            'certificateRepository' => 'App\\Repository\\CertificateRepository',
            'enrollmentsRepository' => 'App\\Repository\\EnrollmentsRepository',
            'entityManager' => '?',
            'lesson' => 'App\\Entity\\Lessons',
            'lessonsRepository' => 'App\\Repository\\LessonsRepository',
        ]);
    }
}
