<?php

namespace ContainerZmxKwhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourses3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.d9rj2d2.App\Entity\Courses' shared service.
     *
     * @return \App\Entity\Courses
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.d9rj2d2": it needs an instance of "App\\Entity\\Courses" but this type has been excluded in "config/services.yaml".');
    }
}
