<?php

namespace ContainerZmxKwhs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLessons2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AIi1cty.App\Entity\Lessons' shared service.
     *
     * @return \App\Entity\Lessons
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AIi1cty": it needs an instance of "App\\Entity\\Lessons" but this type has been excluded in "config/services.yaml".');
    }
}
