<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmxKwhs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmxKwhs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmxKwhs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmxKwhs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZmxKwhs\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZmxKwhs',
    'container.build_id' => 'f07cf5fb',
    'container.build_time' => 1736359775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmxKwhs');
